[tool.poetry]
name = "password-manager"
version = "0.3.0"
description = ""
authors = ["Kant Htay <kokhanthtay@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
